### ISSUE TITLE
Can't install the drivers Mac os Sierra 10.12.3

### ISSUE THREAD

**Issue by Jerrelly** [Wouter1/EMU-driver#100]
when trying to instal is says : 
<img width="572" alt="2017-02-18 13 20 35" src="https://cloud.githubusercontent.com/assets/25859334/23090924/ff1f32d4-f5d3-11e6-9dd7-d1a34eeb332a.png">
can not do nothing..but really need. please help
i have tried a lot of times already..

**Comment by Wouter1** [comment]
@Jerrelly  I just tried to install, for me it works all right.

Looks like your unzipped file is damaged. Can you confirm that your unzipped download contains a v11 directory? Did you start the installer by double clicking installer?

**Comment by Jerrelly** [comment]
@Wouter1 yes it has all the files, i tried different zip-archiver,but nothing work
yes i just double tap on installer 
also forgot to say that i have disabled SIP. 
hope for your soon help

**Comment by Wouter1** [comment]
The first error message about a missing "/Contents" suggests your download is broken. There really should be this directory, it's the core of the kext

Let's first check that your download is correct

execute 
```
openssl sha1 <your downloaded EMU driver.zip> 
```
It should give this number

```
8c083ddd4e29c654d8896bfffa419aa57512feb9
```

**Comment by Jerrelly** [comment]
@Wouter1 so I've checked, it is absolutely the same

**Comment by Wouter1** [comment]
@Jerrelly  great. Then, if you right-click on the EMUUSBAudio.kext inside v11, and select "Show package contents", do you see a "Contents" folder?

**Comment by Jerrelly** [comment]
@Wouter1 yes, and it contain : 
<img width="593" alt="2017-02-20 17 14 54" src="https://cloud.githubusercontent.com/assets/25859334/23120573/11bf0ffe-f787-11e6-87e0-a97beef3b731.png">

**Comment by Wouter1** [comment]
Seems the script is not switching to the correct working directory

Can you edit the install script and add one line

```
pathname=$( cd $(dirname $0) ; pwd -P ) 
cd "$pathname"
```

Maybe you can make that into

```
pathname=$( cd $(dirname $0) ; pwd -P ) 
cd "$pathname"
echo "$pathname"
```

and report back what that echo prints in the console.

**Comment by Jerrelly** [comment]
just add it to end ?

**Comment by Wouter1** [comment]
No, add that echo right under the cd "#pathname"

**Comment by maxkutcher** [comment]
Can not do nothing..but really need. please help!!! Please (macos sierra 10.12.4)
![e-mu problem](https://cloud.githubusercontent.com/assets/27759015/25165696/715b2da4-24e0-11e7-9baf-f5a1a33dd9e0.jpg)

**Comment by Wouter1** [comment]
@Jerrelly  I didn't hear anything anymore. Was this resolved?

**Comment by soupergrouper** [comment]
Had the same problem. Solution was to use default zip file name

**Comment by Wouter1** [comment]
@soupergrouper  thanks for chiming in with a suggestion. So you say that if you rename the zip file and then unzip the renamed file, something goes wrong in the unzipping?

**Comment by soupergrouper** [comment]
@Wouter1 In my case I had old version in 'Downloads' folder. So the name of new download was 'EMU-driver-master 2' by default. I deleted the old one and renamed new to 'EMU-driver-master' and it worked.

**Comment by Wouter1** [comment]
@soupergrouper  thanks for the additional info. I added a do not rename warning to the download instructions. 

I didn't hear back from @Jerrelly  so I suppose this is fixing this.
