### ISSUE TITLE
Can't install the drivers Mac os Sierra 10.12.4

### ISSUE THREAD

**Issue by maxkutcher** [Wouter1/EMU-driver#101]
Can't install the drivers Mac os Sierra 10.12.4! Please Help! After installation, the computer doesn't see sound card (e-mu 0204)
![e-mu problem](https://cloud.githubusercontent.com/assets/27759015/25165827/06227fe6-24e1-11e7-8b9e-9c69ddfbf675.jpg)

**Comment by Wouter1** [comment]
@maxkutcher  Can you please post the log file?
Did you run csrutil ?

**Comment by maxkutcher** [comment]
When csrutil disable - audio computer see sound card!!!

**Comment by maxkutcher** [comment]
When csrutil disable - computer see sound card!!!

**Comment by maxkutcher** [comment]
But when enable doesn't see

**Comment by Wouter1** [comment]
@maxkutcher  Of course, this is according to the installation instructions. Does this solve your issue?

**Comment by maxkutcher** [comment]
Works Everything! Thanks!!!

**Comment by Wouter1** [comment]
@maxkutcher  Great, thanks for the feedback!
