### ISSUE TITLE
10.12.4 macOS Sierra works ultimately good!

### ISSUE THREAD

**Issue by JasF** [Wouter1/EMU-driver#103]
10.12.4 macOS Sierra works ultimately good!

**Comment by Wouter1** [comment]
@JasF  Thanks for the feedback! I'll leave this open (with slightly altered title) if other people want to give thanks or detail that some combination or particular hardware works fine

**Comment by Wouter1** [comment]
I made a new ticket "Confirmations of proper working" because people kept creating new threads anyway. Maybe the new title is cleare.
