### ISSUE TITLE
macOS High Sierra 10.13.4 - E-MU Tracker Pre - Working Driver! 

### ISSUE THREAD

**Issue by longeee** [Wouter1/EMU-driver#111]
Hello!
I confirm that the driver works flawlessly with E-MU Tracker Pre on Hackintosh macOS High Sierra 10.13.4

Thumbs up for your effort ;)

Regards,
longeee

**Comment by Wouter1** [comment]
@longeee  thanks!
I copy your post to the "confirmation of proper working" #109
