### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by timmyleej** [Wouter1/EMU-driver#117]
IS there any way to disable 4 channel mode for emu0204? Every time I open Logic Pro X, It switches emu 0204 to 4 channel and every Im forced to switch it back cause 4 channel mode doesnt work with 0204 anyway.

**Comment by Wouter1** [comment]
@timmyleej  I don't know but I think not. I can't reproduce as I don't have 0204. See also #112.

**Comment by Wouter1** [comment]
@timmyleej you could edit the .plist inside the kernel driver (this is tricky, only for experts) or use the midi setup tools (applications/Utilities) to set it up manually

Also you might try the develop version that I hope is going to fix issues with 0204, see #112.

**Comment by timmyleej** [comment]
@Wouter1 #112 develop version (v11) did nothing to fix this issue, will try plist editing.

**Comment by Wouter1** [comment]
@timmyleej  thanks for testing. Can you report what the EMU driver is logging? 

I'm particularly looking for this message and the messages around it 
"XXX channel YY bit @ ZZ Hz is not supported. Suggesting alternate setting XX"
