### ISSUE TITLE
Catalina no sound

### ISSUE THREAD

**Issue by timmyleej** [Wouter1/EMU-driver#123]
Catalina, 10.15 (19A602). No sound on both 0204 and 0404. No playback sound and no recording as well. Sierra and Mojave were okay on my system. I can see both devices as output and input devices. Tried both low and normal latency drivers.

**Comment by Wouter1** [comment]
@timmyleej  thanks for reporting. Sorry to hear it doesn't work.
You can see the device in your player and select it?
Are you trying to play music? 

I do not have Catalina and probably will not upgrade any time soon. So I can't reproduce/confirm this.

**Comment by timmyleej** [comment]
@Wouter1  yeah, os x see both devices, I can change sample-rate and channel settings by midi-settings app (emu control panel is gray). But still no sound. HDMI and other sound devices work well. I've reverted back to Mojave. But if U can give some advices how to fix it I can test it on another disk drive.

**Comment by Wouter1** [comment]
@timmyleej  Did you check if there are messages from the EMU device in the console (Applications/Utilities)?

**Comment by Wouter1** [comment]
@timmyleej  one more thing, did you give microphone and speaker permission to the sound app you use? I don't know if is exists speaker  permission in catalina but there is mic permission needed for recording in mojave. And technically, mic needs to be working for playback

**Comment by totencham** [comment]
So, it's working on Catalina?

**Comment by Wouter1** [comment]
@totencham  I don't know. One totencham reported an issue on his machine but the problem was not reproduced. Do you have more input on this?

**Comment by totencham** [comment]
No, i'm scared to update because i need working interface...

**Comment by Wouter1** [comment]
@totencham  I can understand. There are about 15 visitors each day so I assume most downloads today are for Catalina and I got only 1 issue report for Catalina so far. But nobody confirmed proper working yet beyond high sierra.

I'm at this moment more concerned about the new laptops with USB-C interface and the required adapters. But that's also because I stick with Mojave for now.

**Comment by timmyleej** [comment]
@Wouter1  Made a fresh install of catalina on separate hard drive, searched for a special permissions for audio devices, there is none. 
No sound, here is console log ,maybe it can help u
![Снимок экрана 2019-10-20 в 20 11 17](https://user-images.githubusercontent.com/44734836/67413346-694f6f80-f5da-11e9-9679-c97c945bbb8a.png)
![Снимок экрана 2019-10-20 в 20 12 20](https://user-images.githubusercontent.com/44734836/67413347-694f6f80-f5da-11e9-852e-77a43117a236.png)
![Снимок экрана 2019-10-20 в 20 12 29](https://user-images.githubusercontent.com/44734836/67413348-69e80600-f5da-11e9-9fa7-64d6f94a4fa2.png)
![Снимок экрана 2019-10-20 в 20 12 44](https://user-images.githubusercontent.com/44734836/67413350-69e80600-f5da-11e9-9acd-9baa17263474.png)

**Comment by Wouter1** [comment]
@timmyleej 

Generally EMU message come from the *kernel* task so other threads can be ignored


First screen shot contains HAL message. It's from a system service connecting the EMU, not from the EMU driver.

The second one shows some possibly serious failures. 
I notice that there is something about "privacy acknowledgment" that might hint towards my suggestion to try

Third one, looks like some more system messages unrelated to EMU

Fourth one, one message from EMU that the engine is starting.

**Comment by Wouter1** [comment]
Checked again, the second one has some weird messages, as if the output channel mOutput.init() has not been called. 

it is called in initHardware

start is called in startUSBStream

According to the manuals https://developer.apple.com/documentation/kernel/ioaudioengine/1812206-inithardware start should call initHardware.

**Comment by bezromval** [comment]
catalina didn't support 32bit app. E-mu driver is 32 bit. This is the only reason that stops me to upgrade to catalina.

**Comment by Wouter1** [comment]
@bezromval  interesting, I did not  realize this.
I'll look if there is a 64 bit setting or compiler option

**Comment by bezromval** [comment]
Thanks. Waiting for good news from you.

**Comment by Wouter1** [comment]
@bezromval why do you think it's 32 bit? I looked into the compiler settings but everything is already set to 64 bit.  The only reference to something 32 bit is

"Apple LLVM 7.1 Warnings : Implicit Conversion to 32 bit type"

And from the docu this is just a compiler warning setting, not anything influencing the build

**Comment by Wouter1** [comment]
Additionally the file command also says it's 64 bit:

```
file v11/EMUUSBAudio.kext/Contents/MacOS/EMUUSBAudio 
v11/EMUUSBAudio.kext/Contents/MacOS/EMUUSBAudio: Mach-O 64-bit kext bundle x86_64

```

**Comment by bezromval** [comment]
Sorry for that. I just look into about this mac system report software and find out that uninstaller only is 32 bit. I don't understand in this much. I just want to e-mu works fine with catalina.

**Comment by Wouter1** [comment]
And the screenshot from timmyleej proves that it actually loaded as the EMU is reporting that it starts the engine.

**Comment by Wouter1** [comment]
@bezromval  uninstaller? I only provide an installer. And it is just a shell script, for which 32/64 bit should be irrelevant.

**Comment by Wouter1** [comment]
@timmyleej can you please report your hardware details, and how you have the EMU connected, and the type of the USB ports on your hardware? 

I still have not heard of anyone else having problems on Catalina so it may be just a problem by 1 user?

**Comment by timmyleej** [comment]
@Wouter1  I have E-MU 0204 and 0404 both connected to my hackintosh installed on chinese motherboard, Xeon E5-1650, C602 Chipset. Connected in usb 2.0 ports, both worked well in Sierra and Mojave.

**Comment by Wouter1** [comment]
@timmyleej  thanks for the details. Direct connection with USB2 ports seems fine.  But it might be an issue with Catalina?

Did you already check the security settings for audio?

**Comment by timmyleej** [comment]
@Wouter1 i think its catalina related issues.
Yeah, I've checked settings. There's nothing input/output related.

**Comment by Wouter1** [comment]
@timmyleej  can you be more specific. There *should* be something input/output related otherwise the security manager will block the audio (at least the input, maybe the output as well in cataline) . What recorder/player program do you use and what are the security settings for audio in/out for that program?

**Comment by timmyleej** [comment]
@Wouter1 I'll check again this evening, I use stock music player (ex-itunes) and youtube in Safari for checking audio playback. And Logic Pro X for record/playback.

**Comment by totencham** [comment]
@Wouter1 is a chance that it will work in Catalina?

**Comment by Wouter1** [comment]
@totencham  sure, there is only one user so far that reported a problem in Catalina.

**Comment by totencham** [comment]
> @totencham sure, there is only one user so far that reported a problem in Catalina.

But this is someone who works?

**Comment by Wouter1** [comment]
@totencham  who is "this"?

**Comment by totencham** [comment]
Has anyone confirmed that it works in Catalina?

**Comment by Wouter1** [comment]
No reports at all yet, #109.

**Comment by grimrian** [comment]
Hello, I upgraded to Catalina without realising there might have been an issue. Fortunately everything works, E-MU interface, Midi, all sample rates. Input, output OK. Turns up everywhere as an audio inout or output option. Version is 4.0.1 originally installed in April. Imac 2017. If anyone needs info from system, let me know.

**Comment by jakubzwierzycki** [comment]
After updating to catalina everything works like a charm,
Ableton usage, emu0404 usb midi config and everything else. On previous osx updates i had to reinstall this driver to restore possibility to choose emu0404 usb midi out / in in ableton preferences. After update to catalina there is no issue like that, so nice work:)

**Comment by Wouter1** [comment]
@timmyleej any news here? 
@totencham  two users reported it all works fine in catalina.  The issue with timmyleej might also be hardware related (he has a hackintosh)

**Comment by totencham** [comment]
Hi! I updated to Catalina on MacBook Pro and i have problem with driver's installation. 
In step. 2 "In a terminal do sudo mount -uw /" returns: 
![image](https://user-images.githubusercontent.com/43566000/69530315-1c144400-0f72-11ea-8dc3-a46dea40dfef.png)

When i start installer script: 
![image](https://user-images.githubusercontent.com/43566000/69530419-4a921f00-0f72-11ea-8489-91e00e898cc3.png)
 and nothing changes...

Anyone can help me?

**Comment by Wouter1** [comment]
@totencham  did you see and follow the additional installation instructions to massage Catalina 

https://github.com/Wouter1/EMU-driver/blob/master/Install.md

**Comment by totencham** [comment]
> @totencham did you see and follow the additional installation instructions to massage Catalina
> 
> https://github.com/Wouter1/EMU-driver/blob/master/Install.md

How was I supposed to not see if I have a problem with this? I did step.1 but on step.2 i was stopped :)

**Comment by Wouter1** [comment]
Thanks for posting the pics.
I see they also have "filesystem protection" now.

Can you try with ```csrutil disable``` insttead of ```csrutil enable --without kext```

**Comment by totencham** [comment]
> Thanks for posting the pics.
> I see they also have "filesystem protection" now.
> 
> Can you try with `csrutil disable` insttead of `csrutil enable --without kext`

You're great! Now, it's working fine! Thank you!

**Comment by Wouter1** [comment]
@totencham  thanks for reporting back! I'll fix the instructions page accordingly.

**Comment by Wouter1** [comment]
Updated the installation docu

**Comment by djjuank** [comment]
Hi, where can I download the driver for the emu 0404  to works with Mac OS Catalina?

Thanks

**Comment by grimrian** [comment]
It does actually work with Catalina on my iMac 2017. 
Regards, Tomas

**Comment by Wouter1** [comment]
@djjuank  FAIK this driver also works on Catalina. I updated the info page to include Catalina.
