### ISSUE TITLE
IRQ Problem on non-Apple macs.

### ISSUE THREAD

**Issue by jefazo2k5** [Wouter1/EMU-driver#134]
This issue affect all Macos versions.

The serial port has to be disabled in bios system, if enabled, the Os system detects wrong IRQ directions, the driver entries in conflict,that results system malfunction when you power on your audio interface.

**Comment by Wouter1** [comment]
@jefazo2k5 what are you talking about, there  is no serial port nor a BIOS system on mac

**Comment by jefazo2k5** [comment]
@Wouter1 this problem is  suffering If you use macos in non-apple  hardware.

**Comment by Wouter1** [comment]
What are you trying to achieve with this ticket? I can not do anything about problems that hackintosh users may run into?

**Comment by jefazo2k5** [comment]
)Sorry don't know what is correct place, i'm new in those enviroments.
i'm not talking about hackintosh, you can use macos on a virtual machine) is only info for other user that use your driver. Sorry for the incorvenence (and my english)

**Comment by Wouter1** [comment]
@jefazo2k5  Yes, thanks for reporting. The info you give seems just a bit out of scope so I'm a bit puzzled. 

Do you want a hackintosh section somewhere?

Is it just that you wanted to report this and can I close this ticket now?

**Comment by jefazo2k5** [comment]
@Wouter1  Is only info for non-apple users .You can close the ticket , or if you prefer , i can delete it.

**Comment by Wouter1** [comment]
I created a section 'hackintosh notes' on the installation page. Thanks!
