### ISSUE TITLE
BIG SUR - 2errors

### ISSUE THREAD

**Issue by Antoha125** [Wouter1/EMU-driver#135]
Hello! I did everything according to the instructions but nothing works. Everything worked for Catalina before! Ask for help !!

E-MU 0204 

![Снимок экрана 2021-01-25 в 20 57 49](https://user-images.githubusercontent.com/21230553/105746029-fd338800-5f4f-11eb-96fc-7b1290799a79.png)

![Снимок экрана 2021-01-25 в 21 01 32](https://user-images.githubusercontent.com/21230553/105746458-821ea180-5f50-11eb-86ef-088015aeb0cd.png)

**Comment by Wouter1** [comment]
@Antoha125  Did you approve using System Preferences? Did you get the pop-up?

**Comment by Antoha125** [comment]
csrutil disable in recovery mode approved.
I did not receive a pop-up window, it is possible that after the permission was renewed, the map was working before the update

**Comment by Wouter1** [comment]
@Antoha125  If you did not get the popup, you have to go to the security panel yourself to allow the extension to run 

Can you try that? System Preferences/Security&Privacy and click "Allow".

**Comment by Antoha125** [comment]
repeated everything from the very beginning 
![7d6d2bc5-effa-4d06-8286-3680f2bbfc10](https://user-images.githubusercontent.com/21230553/105859617-cae06400-5ffd-11eb-8f5e-7559b22e0597.jpg)
![Снимок экрана 2021-01-26 в 17 33 13](https://user-images.githubusercontent.com/21230553/105859629-d03dae80-5ffd-11eb-9fa3-14ed184270fe.png)

**Comment by Wouter1** [comment]
@Antoha125  Why repeat?
Just do what I proposed

**Comment by fotoknet** [comment]
in BIG SUR - SIP does not disabling that way.
after running installer script i just copied file /EMU-driver-master/v11/EMUUSBAudio.kext to folder /Volumes/EFI/EFI/CLOVER/kexts/Other
Now 0204 is working!!!

**Comment by Wouter1** [comment]
@fotoknet  
So how do you disable sip on hackintosh?

**Comment by fotoknet** [comment]
I didn’t turn it off. 
if i try to csrutil disable in recovery mode - after reboot csrutil status showed - all enable. 
i just put kext file in efi folder on efi partition

**Comment by Wouter1** [comment]
@fotoknet  Yes I see. But I really would like to know how people can use the standard installer. And that requires sip disabled
