### ISSUE TITLE
enable audio playback

### ISSUE THREAD

**Issue by Wouter1** [Wouter1/EMU-driver#19]
Maybe we can also fix the playback

**Comment by Wouter1** [comment]
There seems a rather fundamental issue with the existing approach. 

Every write to USB call can write about 64*580 ~ 37kB. 
The ring buffer is 3*4096*6 = 73728 bytes.
So we can easily have one wrap every two USB calls. 

There are 4 framelists for the write. 

So it seems we can have 2 wraps scheduled at any one time.

However, the approach currently has only one 'theWrapRangeDescriptor'

**Comment by Wouter1** [comment]
There also was something wrong with the erase head position. Disabled that for now. 
Playback now seems to work but more testing is needed and also cleanup and refactor of the code

**Comment by Wouter1** [comment]
Tested audio playback on 44.1 and 96kHz, seems to kind of work. Still getting overrun warnings, and more testing is needed.192kHz not yet tested.

**Comment by Wouter1** [comment]
Switching the rate seems to disable the playback connection with the EMU. It seems only 44kHz is actually working.

**Comment by Wouter1** [comment]
The switching of the rate seems to mangle the virtual and physical format of the channels from "mixable" to "unmixable".

HALLab tool can be used to set it back to "mixable" (select EMU, click "info", select "Streams" tab, and in the Output Stream column then change "Virtual format" to "Mixable".

**Comment by Wouter1** [comment]
With that trick, all rates, 48kHz and 96kHz and even 192kHz seem to work fine! I'm a bit suspicious of this, everthing says it's 192kHz and even the lights on the EMU device dim as usual with 192kHz but is this really? I would expect some more bugs

**Comment by Wouter1** [comment]
There was a weird code snip in EMUUSBAudioEngine that added the found LinearPCM formats from the device as isMixable=false AFTER adding them as isMixable=true. I have no idea what's the idea behind that but removing that solved the problem

**Comment by twixst** [comment]
Hi! Im still cant manage playback to work
Before, it did not worked at all, and now audio is playing, but without sound
Im using yosemite, help please

**Comment by Wouter1** [comment]
twixst,
Thanks for your interest in my driver.
Probably you have the problem reported in issue #18. For some computers playback is not yet working. Please check issue #18 and if that sounds like your problem, keep an eye on that ticket. If you think your issue is something different, please report.
