### ISSUE TITLE
midi issues

### ISSUE THREAD

**Issue by Wouter1** [Wouter1/EMU-driver#23]
trambouter reported in #18

Wouter1, when i change sample rate in "Audio MIDI Setup app" nothing happens, and sample rate in select box not each time changed.

**Comment by Wouter1** [comment]
I can not test or fix this as I do not have any midi devices. I will add this to the readme. I suppose the control panel is sufficient to change the sample rate? Or is there a difference with Midi?

**Comment by trambouter** [comment]
emu0204 don't have midi. On creative control panel we can only change the sample rate. In "Audio MIDI Setup app" we can see also number of inputs and outputs channels.

**Comment by Wouter1** [comment]
Ah thanks. I thought you were trying to get MIDI working. This is what this current ticket is about.

I never used a "Audio MIDI Setup app" panel so I have no idea what would happen. The driver seems to be screwing up with 0204 because the number of input and output channels are not matching. Maybe you can try with a balanced number of input and output.

**Comment by Wouter1** [comment]
I have no means here to test anything midi. 
I will close this ticket. Maybe someone that has midi reopens it and then we can do something about this.
