### ISSUE TITLE
Not running volume control, 10.10.3 (yosemite)

### ISSUE THREAD

**Issue by isabido** [Wouter1/EMU-driver#60]
I enjoyed your driver, allowing the frequency change online,
with the original driver entire system freezes, having to turn a button.

But with your driver, I can not handle the volume, I'm testing in yosemite 10.10.3. Is this so?

**Comment by Wouter1** [comment]
Thanks!

Thanks for reporting this issue. 

Lacking volume control is a known issue, #27 . So I close this as a copy of #27 .
